### ISSUE TITLE
请教一下PLIF的复现配置问题

### ISSUE THREAD

**Issue by zhy123-cc** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#16]
我在执行"git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1"出现以下无法解析对象的问题 我匹配这个码回复我找不到，想请问您使用的spikingjelly版本进行复现
![微信图片_20241222214448](https://github.com/user-attachments/assets/0541903c-81af-4e93-af15-166ea7e552ff)

**Comment by fangwei123456** [comment]
是直接git clone还是下载zip得到的spikingjelly，如果是后者是不含git的

**Comment by zhy123-cc** [comment]
> 是直接git clone还是下载zip得到的spikingjelly，如果是后者是不含git的
我是直接下载的，如果我直接下载的话，需要怎么配置呢，还是说我要git clone？

**Comment by fangwei123456** [comment]
直接下载zip里面没有git的历史，所以应该完全按照git clone方式配置：
```
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1
python setup.py install
```

**Comment by zhy123-cc** [comment]
> 直接下载zip里面没有git的历史，所以应该完全按照git clone方式配置：
> 
> ```
> git clone https://github.com/fangwei123456/spikingjelly.git
> cd spikingjelly
> git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1
> python setup.py install
> ```

您好，想请问我按照步骤完成后，运行代码出现错误：Traceback (most recent call last):
  File "/home/code/PLIFcodes/train.py", line 20, in <module>
    import models
  File "/home/code/PLIFcodes/models.py", line 4, in <module>
    from spikingjelly.clock_driven import functional, layer, surrogate, accelrating
ImportError: cannot import name 'accelrating' from 'spikingjelly.clock_driven' (/home/anaconda3/envs/plif/lib/python3.10/site-packages/spikingjelly-0.0.0.0.1-py3.10.egg/spikingjelly/clock_driven/__init__.py)
我重新建了新的环境还是报错这个问题
这个问题会是什么的原因呢？想请教您一下

**Comment by fangwei123456** [comment]
看上去是原来的sj版本没有卸载干净，运行3次 `pip uninstall spikingjelly`试试

**Comment by zhy123-cc** [comment]
> 看上去是原来的sj版本没有卸载干净，运行3次 `pip uninstall spikingjelly`试试

运行了三次都是这样的：WARNING: Skipping spikingjelly as it is not installed.然后我重来了一遍还是有这个问题：ImportError: cannot import name 'accelrating' from 'spikingjelly.clock_driven' ，会是因为torch或者其他包版本的问题吗?

**Comment by fangwei123456** [comment]
```
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1
python setup.py develop
```

用上述方式安装后再看一下报错信息显示的SJ框架路径是不是你的下载路径

**Comment by zhy123-cc** [comment]
> python setup.py develop

现在是显示在我下载路径下边，ImportError: cannot import name 'accelrating' from 'spikingjelly.clock_driven' (/home/code/spikingjelly/spikingjelly/clock_driven/__init__.py)

**Comment by fangwei123456** [comment]
那看上去安装成功了，还报错挺奇怪的。彻底卸载后安装下面这个版本试试（和上面的是一个版本，但不通过git重置而是直接下载历史文件）：

https://github.com/fangwei123456/spikingjelly/archive/73f94ab983d0167623015537f7d4460b064cfca1.zip

**Comment by zhy123-cc** [comment]
> ```
> git clone https://github.com/fangwei123456/spikingjelly.git
> cd spikingjelly
> git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1
> python setup.py develop
> ```
> 
> 用上述方式安装后再看一下报错信息显示的SJ框架路径是不是你的下载路

按这个已经可以了，谢谢您
