### ISSUE TITLE
Issue in loading DVS128Gesture Dataset

### ISSUE THREAD

**Issue by asidddique** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#2]
Hi!

I tried running train_val with DVS128Gesture Dataset but the codes returns the following error:

> train dataset len 0, val dataset len 0
> Traceback (most recent call last):
>   File "./codes/train_val.py", line 232, in <module>
>     train_data_loader = torch.utils.data.DataLoader(
>   File "/home/asgr5/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
>     sampler = RandomSampler(dataset)
>   File "/home/asgr5/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 93, in __init__
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0

The dataset was downloaded from https://research.ibm.com/interactive/dvsgesture/ and stored in the path home/username/datasets/DVS128Gesture. This DVS128Gesture folder contains all files with initials as user* and does not have any seperate folders for train and test. I used the following command to run the simulations:

> python ./codes/train_val.py -init_tau 2.0 -use_max_pool -device cuda:0 -dataset_name DVS128Gesture -log_dir_prefix ./codes/plif_test/logsd -T 20 -max_epoch 1024 -detach_reset -channels 128 -number_layer 5 -split_by number -normalization No
> ne -use_plif

It seems that there is a problem in finding the dataset but it exists already in the given path. Is there any pre-processing required?

**Comment by asidddique** [comment]
I have also used the following lines to create separate train and test samples from the spikingjelly link (https://spikingjelly.readthedocs.io/zh_CN/latest/clock_driven_en/13_neuromorphic_datasets.html):

from spikingjelly.datasets.dvs128_gesture import DVS128Gesture
root_dir = 'D:/datasets/DVS128Gesture'
train_set = DVS128Gesture(root_dir, train=True, data_type='event')
train_set = DVS128Gesture(root_dir, train=True, data_type='frame', frames_number=20, split_by='number')

**Comment by ayeshamkzhh** [comment]
Thankyou.
