### ISSUE TITLE
ModuleNotFoundError: No module named 'loris'

### ISSUE THREAD

**Issue by li-wei-21** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#6]
调用NMNIST数据集的库的时候出现下面的报错，我是按照这个项目提示装的spikingjelly
>>> from spikingjelly.datasets.n_mnist import NMNIST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/liwei/.conda/envs/liwei/lib/python3.8/site-packages/spikingjelly-0.0.0.0.1-py3.8.egg/spikingjelly/datasets/__init__.py", line 5, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/liwei/.conda/envs/liwei/lib/python3.8/site-packages/spikingjelly-0.0.0.0.1-py3.8.egg/spikingjelly/datasets/nav_gesture.py", line 11, in <module>
ModuleNotFoundError: No module named 'loris'

**Comment by fangwei123456** [comment]
https://github.com/neuromorphic-paris/loris
